"""Typed Junjo AI Studio evaluation control and evidence client.

The :mod:`junjo.studio` package is the supported SDK boundary for evaluation
datasets, runs, attempts, exact execution membership, and opt-in trace evidence
queries.  It does not upload telemetry and does not import Studio runtime code.
"""

from .client import StudioClient
from .comparison import (
    RunComparison,
    RunComparisonRow,
    project_run_comparison,
)
from .errors import (
    AttemptExecutionUnavailable,
    ExecutionEvidencePending,
    ExecutionIdentityAmbiguous,
    RunComparisonError,
    StudioAuthenticationError,
    StudioAuthorizationError,
    StudioConflictError,
    StudioContractError,
    StudioError,
    StudioRequestError,
    StudioResponseTooLargeError,
    StudioTransientError,
    StudioValidationError,
)
from .models import (
    TERMINAL_ATTEMPT_STATUSES,
    AttemptCounts,
    AttemptDetail,
    AttemptEvidence,
    AttemptExecutionBind,
    AttemptRead,
    AttemptResultWrite,
    AttemptStatus,
    CaseCreate,
    CaseOrigin,
    CaseRead,
    ConflictResponse,
    DatasetCreate,
    DatasetDetail,
    DatasetList,
    DatasetRead,
    DatasetStatus,
    DatasetSummary,
    ExecutableType,
    ExecutionMembershipItem,
    ExecutionMembershipList,
    ExecutionResolutionConflict,
    ExecutionResolutionRead,
    RunCaseRead,
    RunDetail,
    RunList,
    RunRead,
    RunStart,
    RunStatus,
    RunSummary,
    SemanticExecutionReference,
    StudioDto,
    StudioHealth,
    TargetKind,
    TraceEvidenceRead,
)

__all__ = [
    "TERMINAL_ATTEMPT_STATUSES",
    "AttemptCounts",
    "AttemptDetail",
    "AttemptEvidence",
    "AttemptExecutionBind",
    "AttemptExecutionUnavailable",
    "AttemptRead",
    "AttemptResultWrite",
    "AttemptStatus",
    "CaseCreate",
    "CaseOrigin",
    "CaseRead",
    "ConflictResponse",
    "DatasetCreate",
    "DatasetDetail",
    "DatasetList",
    "DatasetRead",
    "DatasetStatus",
    "DatasetSummary",
    "ExecutableType",
    "ExecutionEvidencePending",
    "ExecutionIdentityAmbiguous",
    "ExecutionMembershipItem",
    "ExecutionMembershipList",
    "ExecutionResolutionConflict",
    "ExecutionResolutionRead",
    "RunCaseRead",
    "RunComparison",
    "RunComparisonError",
    "RunComparisonRow",
    "RunDetail",
    "RunList",
    "RunRead",
    "RunStart",
    "RunStatus",
    "RunSummary",
    "SemanticExecutionReference",
    "StudioAuthenticationError",
    "StudioAuthorizationError",
    "StudioClient",
    "StudioConflictError",
    "StudioContractError",
    "StudioDto",
    "StudioError",
    "StudioHealth",
    "StudioRequestError",
    "StudioResponseTooLargeError",
    "StudioTransientError",
    "StudioValidationError",
    "TargetKind",
    "TraceEvidenceRead",
    "project_run_comparison",
]
