import {
  BackendAgentProjectionFixtureListSchema,
  type BackendAgentProjectionFixture,
} from '../schemas/agent-execution'

/**
 * Parse semantic projections generated by Studio's backend conformance adapter.
 *
 * This boundary intentionally accepts backend results, never normalized spans.
 * Frontend tests therefore exercise the production API contract without
 * implementing a second Agent telemetry interpreter.
 */
export function parseBackendAgentProjectionFixtures(value: unknown): BackendAgentProjectionFixture[] {
  return BackendAgentProjectionFixtureListSchema.parse(value)
}
