"""initial schema

Revision ID: dc353c05b122
Revises:
Create Date: 2026-08-12 22:29:32.641069

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.common.datetime_utils import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = 'dc353c05b122'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('key', sa.String(length=69), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('eval_datasets',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('application_key', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=22), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('locked_at', UTCDateTime(), nullable=True),
    sa.CheckConstraint("(status = 'draft' AND locked_at IS NULL) OR (status = 'locked' AND locked_at IS NOT NULL)", name='eval_datasets_lock_timestamp'),
    sa.CheckConstraint("status IN ('draft', 'locked')", name='eval_datasets_status'),
    sa.CheckConstraint('description IS NULL OR length(CAST(description AS BLOB)) <= 2048', name='eval_datasets_description_bytes'),
    sa.CheckConstraint('length(CAST(application_key AS BLOB)) BETWEEN 1 AND 128', name='eval_datasets_application_key_bytes'),
    sa.CheckConstraint('length(CAST(key AS BLOB)) BETWEEN 1 AND 128', name='eval_datasets_key_bytes'),
    sa.CheckConstraint('length(CAST(name AS BLOB)) BETWEEN 1 AND 256', name='eval_datasets_name_bytes'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_key', 'key', name='uq_eval_datasets_application_key_key')
    )
    with op.batch_alter_table('eval_datasets', schema=None) as batch_op:
        batch_op.create_index('ix_eval_datasets_application_created_id', ['application_key', 'created_at', 'id'], unique=False)

    op.create_table('evaluation_tokens',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('token', sa.String(length=69), nullable=False),
    sa.Column('evaluation_read', sa.Boolean(), nullable=False),
    sa.Column('evaluation_write', sa.Boolean(), nullable=False),
    sa.Column('evidence_read', sa.Boolean(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=22), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint('evaluation_read = 1 OR evaluation_write = 1 OR evidence_read = 1', name='evaluation_tokens_has_scope'),
    sa.CheckConstraint('length(CAST(name AS BLOB)) BETWEEN 1 AND 256', name='evaluation_tokens_name_bytes'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_tokens_token'), ['token'], unique=True)

    op.create_table('eval_cases',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('dataset_id', sa.String(length=22), nullable=False),
    sa.Column('case_key', sa.String(length=128), nullable=False),
    sa.Column('evaluation_name', sa.String(length=256), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=9), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_key', sa.String(length=128), nullable=False),
    sa.Column('target_name', sa.String(length=256), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('expectation_json', sa.Text(), nullable=True),
    sa.Column('evaluator_key', sa.String(length=128), nullable=False),
    sa.Column('evaluator_version', sa.Integer(), nullable=False),
    sa.Column('source_service_namespace', sa.String(length=256), nullable=True),
    sa.Column('source_service_name', sa.String(length=256), nullable=True),
    sa.Column('source_executable_type', sa.String(length=8), nullable=True),
    sa.Column('source_runtime_id', sa.String(length=256), nullable=True),
    sa.Column('source_revision', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint("(origin = 'authored' AND source_service_namespace IS NULL AND source_service_name IS NULL AND source_executable_type IS NULL AND source_runtime_id IS NULL AND source_revision IS NULL) OR (origin = 'generated' AND source_service_namespace IS NOT NULL AND source_service_name IS NOT NULL AND source_executable_type IS NOT NULL AND source_runtime_id IS NOT NULL AND source_revision IS NOT NULL)", name='eval_cases_source_provenance'),
    sa.CheckConstraint("origin IN ('authored', 'generated')", name='eval_cases_origin'),
    sa.CheckConstraint("source_executable_type IS NULL OR source_executable_type IN ('workflow', 'subflow', 'agent')", name='eval_cases_source_executable_type'),
    sa.CheckConstraint("target_kind IN ('node', 'workflow', 'agent')", name='eval_cases_target_kind'),
    sa.CheckConstraint('evaluator_version BETWEEN 1 AND 2147483647', name='eval_cases_evaluator_version'),
    sa.CheckConstraint('expectation_json IS NULL OR (json_valid(expectation_json) AND length(CAST(expectation_json AS BLOB)) <= 16384)', name='eval_cases_expectation_json'),
    sa.CheckConstraint('input_version BETWEEN 1 AND 2147483647', name='eval_cases_input_version'),
    sa.CheckConstraint('json_valid(input_json) AND length(CAST(input_json AS BLOB)) <= 16384', name='eval_cases_input_json'),
    sa.CheckConstraint('length(CAST(case_key AS BLOB)) BETWEEN 1 AND 128', name='eval_cases_case_key_bytes'),
    sa.CheckConstraint('length(CAST(evaluation_name AS BLOB)) BETWEEN 1 AND 256', name='eval_cases_evaluation_name_bytes'),
    sa.CheckConstraint('length(CAST(evaluator_key AS BLOB)) BETWEEN 1 AND 128', name='eval_cases_evaluator_key_bytes'),
    sa.CheckConstraint('length(CAST(target_key AS BLOB)) BETWEEN 1 AND 128', name='eval_cases_target_key_bytes'),
    sa.CheckConstraint('length(CAST(target_name AS BLOB)) BETWEEN 1 AND 256', name='eval_cases_target_name_bytes'),
    sa.CheckConstraint('ordinal >= 1', name='eval_cases_ordinal'),
    sa.CheckConstraint('source_revision IS NULL OR length(source_revision) IN (40, 64)', name='eval_cases_source_revision_length'),
    sa.CheckConstraint('source_runtime_id IS NULL OR length(CAST(source_runtime_id AS BLOB)) BETWEEN 1 AND 256', name='eval_cases_source_runtime_id_bytes'),
    sa.CheckConstraint('source_service_name IS NULL OR length(CAST(source_service_name AS BLOB)) BETWEEN 1 AND 256', name='eval_cases_source_service_name_bytes'),
    sa.CheckConstraint('source_service_namespace IS NULL OR length(CAST(source_service_namespace AS BLOB)) <= 256', name='eval_cases_source_namespace_bytes'),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'case_key', name='uq_eval_cases_dataset_case_key'),
    sa.UniqueConstraint('dataset_id', 'ordinal', name='uq_eval_cases_dataset_ordinal')
    )
    with op.batch_alter_table('eval_cases', schema=None) as batch_op:
        batch_op.create_index('ix_eval_cases_dataset_ordinal_id', ['dataset_id', 'ordinal', 'id'], unique=False)
        batch_op.create_index('ix_eval_cases_source_execution', ['source_service_namespace', 'source_service_name', 'source_executable_type', 'source_runtime_id'], unique=False, sqlite_where=sa.text('source_runtime_id IS NOT NULL'))

    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('dataset_id', sa.String(length=22), nullable=False),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('run_label', sa.String(length=256), nullable=False),
    sa.Column('source_revision', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=22), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.CheckConstraint("(status = 'active' AND completed_at IS NULL) OR (status = 'completed' AND completed_at IS NOT NULL)", name='eval_runs_completion_timestamp'),
    sa.CheckConstraint("status IN ('active', 'completed')", name='eval_runs_status'),
    sa.CheckConstraint('length(CAST(request_key AS BLOB)) BETWEEN 1 AND 128', name='eval_runs_request_key_bytes'),
    sa.CheckConstraint('length(CAST(run_label AS BLOB)) BETWEEN 1 AND 256', name='eval_runs_run_label_bytes'),
    sa.CheckConstraint('length(source_revision) IN (40, 64)', name='eval_runs_source_revision_length'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'request_key', name='uq_eval_runs_dataset_request_key')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index('ix_eval_runs_created_id', ['created_at', 'id'], unique=False)
        batch_op.create_index('ix_eval_runs_dataset_created_id', ['dataset_id', 'created_at', 'id'], unique=False)

    op.create_table('eval_case_attempts',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('run_id', sa.String(length=22), nullable=False),
    sa.Column('case_id', sa.String(length=22), nullable=False),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('subject_service_namespace', sa.String(length=256), nullable=True),
    sa.Column('subject_service_name', sa.String(length=256), nullable=True),
    sa.Column('subject_executable_type', sa.String(length=8), nullable=True),
    sa.Column('subject_runtime_id', sa.String(length=256), nullable=True),
    sa.Column('execution_bound_at', UTCDateTime(), nullable=True),
    sa.Column('recorded_at', UTCDateTime(), nullable=True),
    sa.CheckConstraint("(status = 'queued' AND reason IS NULL AND duration_ms IS NULL AND recorded_at IS NULL) OR (status IN ('passed', 'failed') AND reason IS NOT NULL AND subject_runtime_id IS NOT NULL AND recorded_at IS NOT NULL) OR (status = 'error' AND reason IS NOT NULL AND recorded_at IS NOT NULL)", name='eval_case_attempts_terminal_fields'),
    sa.CheckConstraint("status IN ('queued', 'passed', 'failed', 'error')", name='eval_case_attempts_status'),
    sa.CheckConstraint("subject_executable_type IS NULL OR subject_executable_type IN ('workflow', 'subflow', 'agent')", name='eval_case_attempts_subject_executable_type'),
    sa.CheckConstraint('(subject_service_namespace IS NULL AND subject_service_name IS NULL AND subject_executable_type IS NULL AND subject_runtime_id IS NULL AND execution_bound_at IS NULL) OR (subject_service_namespace IS NOT NULL AND subject_service_name IS NOT NULL AND subject_executable_type IS NOT NULL AND subject_runtime_id IS NOT NULL AND execution_bound_at IS NOT NULL)', name='eval_case_attempts_subject_execution'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms BETWEEN 0 AND 86400000', name='eval_case_attempts_duration'),
    sa.CheckConstraint('reason IS NULL OR length(CAST(reason AS BLOB)) BETWEEN 1 AND 4096', name='eval_case_attempts_reason_bytes'),
    sa.CheckConstraint('subject_runtime_id IS NULL OR length(CAST(subject_runtime_id AS BLOB)) BETWEEN 1 AND 256', name='eval_case_attempts_subject_runtime_id_bytes'),
    sa.CheckConstraint('subject_service_name IS NULL OR length(CAST(subject_service_name AS BLOB)) BETWEEN 1 AND 256', name='eval_case_attempts_subject_service_name_bytes'),
    sa.CheckConstraint('subject_service_namespace IS NULL OR length(CAST(subject_service_namespace AS BLOB)) <= 256', name='eval_case_attempts_subject_namespace_bytes'),
    sa.ForeignKeyConstraint(['case_id'], ['eval_cases.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_id', name='uq_eval_case_attempts_run_case')
    )
    with op.batch_alter_table('eval_case_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_eval_case_attempts_case_run', ['case_id', 'run_id'], unique=False)
        batch_op.create_index('ix_eval_case_attempts_run_status', ['run_id', 'status'], unique=False)
        batch_op.create_index('uq_eval_case_attempts_subject_execution', ['subject_service_namespace', 'subject_service_name', 'subject_executable_type', 'subject_runtime_id'], unique=True, sqlite_where=sa.text('subject_runtime_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_case_attempts', schema=None) as batch_op:
        batch_op.drop_index('uq_eval_case_attempts_subject_execution', sqlite_where=sa.text('subject_runtime_id IS NOT NULL'))
        batch_op.drop_index('ix_eval_case_attempts_run_status')
        batch_op.drop_index('ix_eval_case_attempts_case_run')

    op.drop_table('eval_case_attempts')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_runs_dataset_created_id')
        batch_op.drop_index('ix_eval_runs_created_id')

    op.drop_table('eval_runs')
    with op.batch_alter_table('eval_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_cases_source_execution', sqlite_where=sa.text('source_runtime_id IS NOT NULL'))
        batch_op.drop_index('ix_eval_cases_dataset_ordinal_id')

    op.drop_table('eval_cases')
    with op.batch_alter_table('evaluation_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_tokens_token'))

    op.drop_table('evaluation_tokens')
    with op.batch_alter_table('eval_datasets', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_datasets_application_created_id')

    op.drop_table('eval_datasets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
