# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """-----------------------------------------------------------------------------
    Public-Facing Services (on ingestion-service)
    -----------------------------------------------------------------------------

    AuthService provides a public endpoint for clients to exchange an API key
    for a short-lived JWT. This is the single point of contact for auth.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetToken = channel.unary_unary(
                '/ingestion.AuthService/GetToken',
                request_serializer=auth__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.GetTokenResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """-----------------------------------------------------------------------------
    Public-Facing Services (on ingestion-service)
    -----------------------------------------------------------------------------

    AuthService provides a public endpoint for clients to exchange an API key
    for a short-lived JWT. This is the single point of contact for auth.
    """

    def GetToken(self, request, context):
        """GetToken exchanges a Junjo API Key for a JWT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=auth__pb2.GetTokenRequest.FromString,
                    response_serializer=auth__pb2.GetTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """-----------------------------------------------------------------------------
    Public-Facing Services (on ingestion-service)
    -----------------------------------------------------------------------------

    AuthService provides a public endpoint for clients to exchange an API key
    for a short-lived JWT. This is the single point of contact for auth.
    """

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.AuthService/GetToken',
            auth__pb2.GetTokenRequest.SerializeToString,
            auth__pb2.GetTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InternalAuthServiceStub(object):
    """-----------------------------------------------------------------------------
    Internal Services
    -----------------------------------------------------------------------------

    InternalAuthService provides a private API for the ingestion-service to
    validate API keys and receive signed JWTs from the backend.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeApiKeyForJwt = channel.unary_unary(
                '/ingestion.InternalAuthService/ExchangeApiKeyForJwt',
                request_serializer=auth__pb2.ExchangeApiKeyForJwtRequest.SerializeToString,
                response_deserializer=auth__pb2.ExchangeApiKeyForJwtResponse.FromString,
                _registered_method=True)


class InternalAuthServiceServicer(object):
    """-----------------------------------------------------------------------------
    Internal Services
    -----------------------------------------------------------------------------

    InternalAuthService provides a private API for the ingestion-service to
    validate API keys and receive signed JWTs from the backend.
    """

    def ExchangeApiKeyForJwt(self, request, context):
        """ExchangeApiKeyForJwt validates an API key and returns a signed JWT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalAuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeApiKeyForJwt': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeApiKeyForJwt,
                    request_deserializer=auth__pb2.ExchangeApiKeyForJwtRequest.FromString,
                    response_serializer=auth__pb2.ExchangeApiKeyForJwtResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingestion.InternalAuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ingestion.InternalAuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalAuthService(object):
    """-----------------------------------------------------------------------------
    Internal Services
    -----------------------------------------------------------------------------

    InternalAuthService provides a private API for the ingestion-service to
    validate API keys and receive signed JWTs from the backend.
    """

    @staticmethod
    def ExchangeApiKeyForJwt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ingestion.InternalAuthService/ExchangeApiKeyForJwt',
            auth__pb2.ExchangeApiKeyForJwtRequest.SerializeToString,
            auth__pb2.ExchangeApiKeyForJwtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
