# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\tingestion\"\"\n\x0fGetTokenRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"3\n\x10GetTokenResponse\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\".\n\x1b\x45xchangeApiKeyForJwtRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"?\n\x1c\x45xchangeApiKeyForJwtResponse\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\x32T\n\x0b\x41uthService\x12\x45\n\x08GetToken\x12\x1a.ingestion.GetTokenRequest\x1a\x1b.ingestion.GetTokenResponse\"\x00\x32\x80\x01\n\x13InternalAuthService\x12i\n\x14\x45xchangeApiKeyForJwt\x12&.ingestion.ExchangeApiKeyForJwtRequest\x1a\'.ingestion.ExchangeApiKeyForJwtResponse\"\x00\x42\rZ\x0b.;proto_genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013.;proto_gen'
  _globals['_GETTOKENREQUEST']._serialized_start=25
  _globals['_GETTOKENREQUEST']._serialized_end=59
  _globals['_GETTOKENRESPONSE']._serialized_start=61
  _globals['_GETTOKENRESPONSE']._serialized_end=112
  _globals['_EXCHANGEAPIKEYFORJWTREQUEST']._serialized_start=114
  _globals['_EXCHANGEAPIKEYFORJWTREQUEST']._serialized_end=160
  _globals['_EXCHANGEAPIKEYFORJWTRESPONSE']._serialized_start=162
  _globals['_EXCHANGEAPIKEYFORJWTRESPONSE']._serialized_end=225
  _globals['_AUTHSERVICE']._serialized_start=227
  _globals['_AUTHSERVICE']._serialized_end=311
  _globals['_INTERNALAUTHSERVICE']._serialized_start=314
  _globals['_INTERNALAUTHSERVICE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
