services:
  backend:
    image: junjo-rsmig-app:proto
    volumes: !override
      - ${JUNJO_HOST_DB_DATA_PATH}:/app/.dbdata
    environment:
      JUNJO_DIAGNOSTIC_BOUNDED_DEDUPE: "true"
      JUNJO_DIAGNOSTIC_HOT_RETRY: "true"
  ingestion:
    image: junjo-rsmig-ingestion:0.85.0
    volumes: !override
      - ${JUNJO_HOST_DB_DATA_PATH}:/app/.dbdata
  auth-proxy:
    image: junjo-rsmig-auth-proxy:local
