services:
  backend:
    image: junjo-composable-baseline:local
    volumes: !override
      - ${JUNJO_HOST_DB_DATA_PATH}:/app/.dbdata
  ingestion:
    image: junjo-adk-fc0e-ingestion:latest
    volumes: !override
      - ${JUNJO_HOST_DB_DATA_PATH}:/app/.dbdata
