services:
  backend:
    image: junjo-rsmig-rust-backend:system
    volumes: !override
      - ${JUNJO_HOST_DB_DATA_PATH}:/app/.dbdata
    environment:
      JUNJO_DIAGNOSTIC_DF_DISABLE_RUNTIME_CACHES: "true"
  ingestion:
    image: junjo-rsmig-ingestion:local
    volumes: !override
      - ${JUNJO_HOST_DB_DATA_PATH}:/app/.dbdata
  auth-proxy:
    image: junjo-rsmig-python-backend:local
